---
title: "Preps_and_explore.Rmd"
author: "johannaschillig"
date: '2022-06-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Loading important libraries

library(remotes)
library(tidyverse)
library(readr)
library(ggplot2)
library(tidyselect)
library(dplyr)
library(boot)
library(brms)
library(parallel)
```


```{r pressure, echo=FALSE}
#renaming condition, stereotype and response for convenience purposes

raw_data<- read_csv("/Users/johannaschillig/Downloads/final_version_resuuults.csv")
renamed_chart <- raw_data
renamed_chart$response[renamed_chart$response == "first"] <- "female_response"
renamed_chart$response[renamed_chart$response == "second"] <- "male_response"
renamed_chart$condition[renamed_chart$condition == "male"] <- "gramm_male"
renamed_chart$condition[renamed_chart$condition == "female"] <- "gramm_female"
renamed_chart$condition[renamed_chart$condition == "gender-neutral"] <- "gramm_neutral"
renamed_chart$stereotype[renamed_chart$stereotype == "male"] <- "stereo_male"
renamed_chart$stereotype[renamed_chart$stereotype == "female"] <- "stereo_female"
renamed_chart$stereotype[renamed_chart$stereotype == "neutral"] <- "stereo_neutral"
renamed_chart$gender[renamed_chart$gender == "divers"] <- "diverse"
renamed_chart$gender[renamed_chart$gender == "weiblich"] <- "female"
renamed_chart$gender[renamed_chart$gender == "männlich"] <- "male"
print(renamed_chart)
```

```{r}
# Extracting information about spoken languages
language_checks <- renamed_chart%>%
  select(languages, submission_id)%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  filter(languages != "deutsch", languages != "Deutsch")%>%
print(language_checks)
```

```{r}
# Extracting information about highest education level
education_checks <- renamed_chart%>%
  select(education, submission_id)%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  filter(education != "Abitur")%>%
  print(education_checks)
  
```

```{r}
# Age and gender analysis 

# Overall analysis and visualization of participants' gender
count_chart <- renamed_chart %>% 
  filter(submission_id != 3505 & submission_id != 3435)%>%
  group_by(gender) %>% 
  summarise(count = n()/108)%>%
  select(count, gender)%>%
  print(count_chart)

count_chart_plot <- ggplot(data = count_chart, mapping = aes(x = gender, y = count, fill = gender)) + geom_col() +
  scale_fill_manual(values=c("plum4", "tomato4", "steelblue2"))+
  labs(
    x = 'Participant Gender',
    y = 'Count',
    title = "Gender Profile of Participants")  

print(count_chart_plot)

# Analysis and plotting of participants' age
age_calc <- renamed_chart%>%
  group_by(age, gender)%>% 
  summarise(mean_age = mean(age))%>%
  print(age_calc)
  print(mean_age)
  
max_calc <- renamed_chart%>%
  summarise(max_age = max(age))%>%
  print(max_age)
min_calc <- renamed_chart%>%
  summarise(min_age = min(age))%>%
  print(min_age)

renamed_chart%>%
  select(age, gender)
  
age_plot <- ggplot(data = renamed_chart, mapping = aes(x = gender, y = age, color = gender)) +
  geom_boxplot(alpha = 0.1) + 
  scale_color_manual(values=c("plum4", "tomato4", "steelblue2"))+
  labs(
    x = 'Participant Gender',
    y = 'Participant Age',
    title = "Age Profile of Participants") 
  
print(age_plot)

# Adding information together
library(cowplot)
cowplot::plot_grid(
  # plots to combine
  age_plot, 
  count_chart_plot
) + theme_dark()
```

```{r}
#### Basic checks for general response bias ###

#Counting how often a male and female response were given

basic_check <- renamed_chart%>%
rename(gender_of_the_participants = gender)%>% 
  
select(response, gender_of_the_participants, condition, submission_id)%>%
filter(submission_id != 3505 & submission_id != 3435)%>%
filter(response == 'female_response' | response == 'male_response')%>%
  
group_by(response)

ggplot(data = basic_check, mapping = aes(x = response, fill =gender_of_the_participants)) +
  geom_bar() +
  scale_fill_manual(values=c("plum4", "tomato4", "steelblue2"))+
  #facet_wrap( ~ gender) +
    labs(
    x = 'Repsonse',
    y = 'Count',
    title = "Basic investigation of general response biases")

### Averting the conclusion that distribution is caused by internal error ###

# Checking if stereotypes occur with equal count

basic_check_chart <- renamed_chart%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  select(stereotype)%>%
  group_by(stereotype)%>%
  filter(stereotype != "NA")%>%
  count()%>%
  rename(count_of_stereotypes = n)%>%
  print()
 
# Checking if conditions occur with equal count 
basic_check_chart2 <- renamed_chart%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  select(condition)%>%
  group_by(condition)%>%
  filter(condition != "NA")%>%
  count()%>%
  rename(count_of_conditions = n)%>%
  print()  



```

```{r}
### Explorative analysis of reaction times depending on grammatical form and stereotype ###

# Comparing reaction times for different condition, stereotype combinations
temporal_info <- renamed_chart%>%
  select(RT, condition, stereotype, gender, role_noun, phase, submission_id)%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  filter(condition == "gramm_female" | condition == "gramm_male" | condition == "gramm_neutral")%>%
  filter(RT <= 120000)
print(temporal_info)
  
plot <- ggplot(data = temporal_info, mapping = aes(x = condition, y = RT, fill = condition)) + 
facet_grid( ~ stereotype) + 
geom_boxplot()+
  scale_fill_manual(values=c("deeppink4", "deepskyblue4", "darkviolet"))
print(plot)

# Adding column for congruent and incongruent condition (congruent: stereotype == condition, incongruent: stereotype != condition)
congruency_info <- raw_data
congruency_info$condition[raw_data$condition == "gender-neutral"] <- "neutral"

  congru_chart <- congruency_info%>%
  mutate(congruency = condition == stereotype)%>%
  select(condition, stereotype,response, congruency, RT, phase, gender, role_noun)%>%
  print(congruency_info)
  

# Cutting off responses with too long reaction time and calculating mean RT for (in)congruent trials
RT_congruency_info <- congru_chart%>%
  filter(phase == 1, RT <= 120000)%>%
  group_by(congruency)%>%
  summarize(mean_RT = mean(RT))
print(RT_congruency_info)

# Computing the mean RT for the different role nouns and arrange them in descending order
congru2 <-  congruency_info%>%
  filter(RT <= 120000)%>%
  filter(role_noun != "Chirurg*innen")%>%
  group_by(role_noun)%>%
  summarize( mean_RT = mean(RT))%>%
  arrange(desc(mean_RT))
print(congru2)

congru2

plot_them <- ggplot(data = congru2, mapping = aes(x = reorder(role_noun, -mean_RT), y = mean_RT, fill = role_noun))+ geom_col()
print(plot_them)

# Checking if GNL triggers longer RT

gnl_RT_check <- raw_data%>%
  select(RT, condition, phase)%>%
  filter(RT <= 120000)%>%
  filter(phase == 1)%>%
  group_by(condition)%>%
  summarise(mean_RT_cond = mean(RT))
  print(gnl_RT_check)
```


```{r}
### Justification of the Misersky role nouns ###

#Transforming table so that stereotypical information is ecoded numerically
stereo_check_transform <- renamed_chart

stereo_check_transform$response[stereo_check_transform$response == "Neutral"] <- as.numeric(0.5)
stereo_check_transform$response[stereo_check_transform$response == "Weiblich"] <- as.numeric(1)
stereo_check_transform$response[stereo_check_transform$response == "Männlich"] <- as.numeric(0)
print(stereo_check_transform)

stereo_check_filter <- stereo_check_transform%>%
  select(stereotype, role_noun, response, phase, stereotype, submission_id)%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  filter(phase == 3)%>%
  mutate(numeric_response = as.numeric(response))%>%
  print(stereo_check_filter)

# Computing mean of stereotypical assessment of phase 3
stereo_value <- stereo_check_filter%>%
  group_by(role_noun)%>%
  summarise(mean_val = mean(numeric_response))%>%
  arrange(desc(mean_val))%>%
  mutate(stereo_var = mean_val)
  stereo_value$stereo_var[stereo_value$stereo_var >= 0.485] <- "f"
  stereo_value$stereo_var[stereo_value$stereo_var <= 0.318] <- "m"
  
  
  print(stereo_value)
  
  stereo_value$stereo_var[stereo_value$stereo_var <= 0.485] <- "n"
  
  print(stereo_value)


# Plotting the stereotypes from the data
  
ggplot(data = stereo_value, mapping = aes(x = role_noun, y = mean_val, fill = role_noun )) +
geom_col()

#Misersky tibble 

misersky_results <- tribble(
  ~role_noun,                       ~"julia_count",       ~"stereotype",
  "Astronaut*innen",                     0.24,                 "m",     
  "Autor*innen von Liebesromanen",       0.70,                 "f",
  "Babysitter*innen",                    0.83,                 "f",
  "Balletttänzer*innen",                 0.75,                 "f",
  "Bürgermeister*innen",                 0.28,                 "m",
  "Chirgur*innen",                       0.29,                 "m",
  "Ernährungsberater*innen",             0.70,                 "f",
  "Florist*innen",                       0.79,                 "f",
  "Flugbegleiter*innen",                 0.75,                 "f",
  "Fotograf*innen",                      0.50,                 "n",
  "Friseur*innen",                       0.78,                 "f",
  "Grundschullehrer*innen",              0.79,                 "f",
  "Haushälter*innen",                    0.78,                 "f",
  "Hundehalter*innen",                   0.50,                 "n",
  "Immobilienmakler*innen",              0.45,                 "n",
  "Journalist*innen",                    0.52,                 "n",
  "Kassierer*innen",                     0.74,                 "f",
  "Kindergärtner*innen",                 0.82,                 "f",
  "Künstler*innen",                      0.50,                 "n",
  "Manager*innen",                       0.28,                 "m",
  "Mediziner*innen",                     0.48,                 "n",  
  "Metzger*innen",                       0.26,                 "m",
  "Mieter*innen",                        0.52,                 "n",
  "Mörder*innen",                        0.28,                 "m",
  "Patient*innen",                       0.51,                 "n",
  "Pilot*innen",                         0.23,                 "m",
  "politische Aktivist*innen",           0.46,                 "n",
  "Präsident*innen",                     0.17,                 "m",  
  "Privatdetektiv*innen",                0.30,                 "m",
  "Programmierer*innen",                 0.20,                 "m",
  "Psychiater*innen",                    0.51,                 "n",
  "Schneider*innen",                     0.71,                 "f",
  "Soldat*innen",                        0.18,                 "m",
  "Sportler*innen",                      0.47,                 "n",
  "Student*innen",                       0.55,                 "n",
  "Taxifahrer*innen",                    0.24,                 "m"
)
print(misersky_results)

# Chart that shows Misersky vs. experimentally found stereotypes

comparison_chart <- full_join(misersky_results, stereo_value, by = "role_noun")%>%
  select(role_noun, julia_count, mean_val, stereotype, stereo_var)%>%
print(comparison_chart)

#Excluding role nouns with stereotype switch

difference_chart <- comparison_chart%>%
  filter(stereotype != stereo_var)
print(difference_chart)


```


```{r}
# Creating a chart in which Misersky counts and present counts stand next to each other

comparison_chart
clean_chart <- comparison_chart%>%
  rename("role noun" = role_noun, "mean (Misersky et al.)" = julia_count, "mean (encountered)" = mean_val, "stereotype (Misersky et al.)" = stereotype, "stereotype (encountered)" = stereo_var)
print(clean_chart)

towards_plot <- clean_chart%>%
  select("mean (encountered)", "stereotype (encountered)", "role noun")
  


```

```{r}

### Manipulation of the data representation ###

#extracting responses of phase 2

responded_gender_try <- renamed_chart%>%
  select(response, submission_id, phase)%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  filter(response == "female_response" | response == "male_response")
  print(responded_gender_try)
 
#extracting responses of phase 1
  
responded_name_try <- renamed_chart%>%
    
  select(response, submission_id, phase)%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  filter(phase == 1)
  print(responded_name_try)
  
#creating a chart in which responded name and corresponding button click stand next to each other
  
response_all_try <- bind_cols(responded_gender_try, responded_name_try)
  print(response_all_try)
  
response_final_try <- response_all_try%>%
 select(response...4, response...1, submission_id...5)%>%  
  mutate(r_name = response...4,
         r_gender = response...1,
         sub_id = submission_id...5)%>%
  select(sub_id, r_name, r_gender)
  print(response_final_try)  
  
#extracting the condition info and stereotype info

condition_chart <- renamed_chart%>%
  
  select(condition, submission_id)%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  filter(condition != "NA")
  print(condition_chart)

stereotype_chart <- renamed_chart%>%
  
  select(stereotype, trial_name, submission_id)%>%
  filter(submission_id != 3505 & submission_id != 3435)%>%
  filter(trial_name == "filler_sentences")
  print(stereotype_chart)  


full_info_chart <- bind_cols(condition_chart, stereotype_chart)
  print(full_info_chart)
  
the_onex <- bind_cols(response_final_try, full_info_chart)%>%
  select(sub_id, condition, r_name, r_gender, stereotype)%>%
  print(the_onex)  
  
the_onexy <- the_onex%>%
  rename("responded_name" = r_name,
         "responded_gender" = r_gender)
print(the_onexy)
 
  

```




















