---
title: "Figures"
author: "johannaschillig"
date: "2022-07-19"
output: html_document
---

```{r}
# Loading libraries
# not all are needed, but loaded by default
library(remotes)
library(tidyverse)
library(readr)
library(ggplot2)
library(tidyselect)
library(dplyr)
library(boot)
library(brms)
library(parallel)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### Plotting the comparison of similarities between target role nouns and männer and frauen

# Creating the tibble for the self-made corpus

cosine_sim_tibble <- tribble(
  ~target_word,  ~"target_role_noun",  ~"cosine_similarity",
   "männer",    "lehrerinnen",           0.1856,
   "frauen",    "lehrerinnen",           0.2463,
   "männer",    "lehrer",                0.1086,
   "frauen",    "lehrer",                0.0849,
   "männer",    "bürgerinnen",          -0.0436,
   "frauen",    "bürgerinnen",           0.0466,
   "männer",    "bürger",                0.0741,
   "frauen",    "bürger",               -0.0212,
   "männer",    "expertinnen",          -0.1212,        
   "frauen",    "expertinnen",           0.0466,
   "männer",    "experten",              0.1655,
   "frauen",    "experten",              0.0342,
   "männer",    "forscherinnen",          0.1818,       
   "frauen",    "forscherinnen",          0.1872,       
   "männer",    "forscher",               0.1210,
   "frauen",    "forscher",               0.0700,
   "männer",    "wählerinnen",            0.0313,       
   "frauen",    "wählerinnen",           -0.363, 
   "männer",    "wähler",                -0.1627,
   "frauen",    "wähler",                -0.1215,
   "männer",    "urheberinnen",          -0.1145,       
   "frauen",    "urheberinnen",          -0.1068, 
   "männer",    "urheber",                0.1274,
   "frauen",    "urheber",                0.1786,
   "männer",    "nutzerinnen",            0.0260,       
   "frauen",    "nutzerinnen",            0.1776, 
   "männer",    "nutzer",                 0.1046,
   "frauen",    "nutzer",                 0.1278,
   "männer",    "schülerinnen",           0.1431,       
   "frauen",    "schülerinnen",           0.2327, 
   "männer",    "schüler",                0.1029,
   "frauen",    "schüler",               -0.0660,
   "männer",    "sportlerinnen",         -0.1616,       
   "frauen",    "sportlerinnen",         -0.1413, 
   "männer",    "sportler",               0.2295,
   "frauen",    "sportler",               0.1107,
   "männer",    "politikerinnen",        -0.0431,       
   "frauen",    "politikerinnen",         0.11078, 
   "männer",    "politiker",              0.0724,
   "frauen",    "politiker",             -0.0105
)
print(cosine_sim_tibble)
```
```{r}
# Plotting results from the self-made corpus

plot_cosssim <- ggplot(data = cosine_sim_tibble, aes(x = target_role_noun, y = cosine_similarity, color = target_word, fill = target_word)) +
  facet_grid(~"target_word") +
  geom_point(shape = 23, size = 3 )
print(plot_cosssim)
```
```{r}
### Plotting the comparison of similarities between target role nouns and männer and frauen

# Creating tibbles for the pretrained corpus

# masculine generic role nouns
cosine_sim_tibble_pretrained <- tribble(
  ~target_word,  ~"target_role_noun",  ~"cosine_similarity",  ~"condition",
   "Mann",             "Lehrer",           0.3208,                 "MG",
   "Frau",             "Lehrer",           0.3095,                 "MG",
   "Mann",             "Sportler",         0.3095,                 "MG",
   "Frau",             "Sportler",         0.3532,                 "MG",
   "Mann",             "Bürgermeister",    0.2219,                 "MG",
   "Frau",             "Bürgermeister",    0.2622,                 "MG",
   "Mann",             "Trainer",          0.2650,                 "MG",
   "Frau",             "Trainer",          0.1888,                 "MG",
   "Mann",             "Spieler",          0.3925,                 "MG",
   "Frau",             "Spieler",          0.2955,                 "MG",
   "Mann",             "Schüler",          0.3021,                 "MG",
   "Frau",             "Schüler",          0.2865,                 "MG",
   "Mann",             "Mitarbeiter",      0.3754,                 "MG",
   "Frau",             "Mitarbeiter",      0.3452,                 "MG",
   "Mann",             "Besucher",         0.2671,                 "MG",
   "Frau",             "Besucher",         0.2665,                 "MG",
   "Mann",             "Bürger",           0.3390,                 "MG",
   "Frau",             "Bürger",           0.3512,                 "MG",
   "Mann",             "Teilnehmer",       0.3101,                 "MG",
   "Frau",             "Teilnehmer",       0.2832,                 "MG"
) 
print(cosine_sim_tibble_pretrained)

# grammatical neutral role nouns
tibble_GNL_cossim <-tribble(
  ~target_word,  ~"target_role_noun",  ~"cosine_similarity",  ~"condition",
   "Mann",             "Mitglied",         0.2551,                 "GNL",
   "Frau",             "Mitglied",         0.2791,                 "GNL",
   "Mann",             "Gast",             0.4110,                 "GNL",
   "Frau",             "Gast",             0.3660,                 "GNL",
   "Mann",             "Person",           0.6131,                 "GNL", 
   "Frau",             "Person",           0.6415,                 "GNL",
   "Mann",             "Pflegekraft",      0.4206,                 "GNL", 
   "Frau",             "Pflegekraft",      0.4814,                 "GNL"
)
print(tibble_GNL_cossim)
```
```{r}
### Visualization of the results using a scatter plot

plot_cossim_pretrained_MG <- ggplot(data = cosine_sim_tibble_pretrained, aes(x = target_role_noun, y = cosine_similarity, color = target_word, fill = target_word)) +
  geom_point(shape = 23, size = 3 )
print(plot_cossim_pretrained_MG)

plot_cossim_pretrained_GNL <- ggplot(data = tibble_GNL_cossim, aes(x = target_role_noun, y = cosine_similarity, color = target_word, fill = target_word)) +
  geom_point(shape = 23, size = 3 )
print(plot_cossim_pretrained_GNL)
```

